### PR TITLE
Project Lombok

### PR DESCRIPTION
**Pull request by Antrakos**
Project Lombok support

### CODE REVIEW

**Comment by ITsvetkoFF** [comment]
https://projectlombok.org/ ?

What is it? 

Do we have issue number 169?

**Comment by Antrakos** [comment]
Nope. That's just a proposition. So I added "question" tag.

**Comment by Antrakos** [comment]
Project Lombok is an utilite to replace boilerplate code. Generally it's used for convenoent and flexible creating POJOs, but lib has some another features too

**Comment by ghost** [comment]
I don't think we need to use Lombok now. It's not good time to add dependencies to reduce development efforts when you guys are still not confident enough to implement entities carefully.

**Pull request closed without merging**
